### ISSUE TITLE
sidebar stopped working

### ISSUE THREAD

**Issue by dpshelio** [OpenAstronomy/Universe_OA#90]
The latest run show these warnings
```
WARNING: PluginManager: Plugin sidebar from /github/workspace/plugins/sidebar/sidebar.plugin does not specify Nikola configuration - plugin will not be loaded
WARNING: PluginManager: Please add a [Nikola] section to the {plugin_file} file with a PluginCategory entry
WARNING: PluginManager: Some plugins failed to load. Please review the above warning messages.
WARNING: PluginManager: You may need to update some plugins (from plugins.getnikola.com) or to fix their .plugin files.
```

**Comment by dpshelio** [comment]
Fixed by 8405363b8b03ed6493f5bf1fb43a4d47f4f5872f
As required by [Nikola v8.3](https://www.getnikola.com/changes.html#for-plugin-developers)

**Comment by bsipocz** [comment]
We only have 6 contributors listed in the sidebar, so something is still not OK.
